blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Discussions
    url: https://github.com/neurostunt/satTrack/discussions
    about: Ask questions and discuss ideas
  - name: ðŸ“š Documentation
    url: https://github.com/neurostunt/satTrack#readme
    about: Check the README for documentation
